# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Harry\Documents\PyQtProjects\socket_func_pyqt\ui\pick_point.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PickPoint(object):
    def setupUi(self, PickPoint):
        PickPoint.setObjectName(_fromUtf8("PickPoint"))
        PickPoint.resize(944, 672)
        PickPoint.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        PickPoint.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        PickPoint.setSizeGripEnabled(True)
        self.pp_webView = QtWebKit.QWebView(PickPoint)
        self.pp_webView.setGeometry(QtCore.QRect(0, 0, 1031, 741))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pp_webView.sizePolicy().hasHeightForWidth())
        self.pp_webView.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pp_webView.setFont(font)
        self.pp_webView.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pp_webView.setMouseTracking(True)
        self.pp_webView.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pp_webView.setUrl(QtCore.QUrl(_fromUtf8("file:///C:/Users/Harry/Documents/PyQtProjects/socket_func_pyqt/websrc/pick_point_2.html")))
        self.pp_webView.setObjectName(_fromUtf8("pp_webView"))
        self.pp_testbrowser = QtGui.QTextBrowser(PickPoint)
        self.pp_testbrowser.setGeometry(QtCore.QRect(480, 510, 401, 121))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pp_testbrowser.setFont(font)
        self.pp_testbrowser.setObjectName(_fromUtf8("pp_testbrowser"))
        self.pick_send_btn = QtGui.QPushButton(PickPoint)
        self.pick_send_btn.setGeometry(QtCore.QRect(390, 510, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_send_btn.setFont(font)
        self.pick_send_btn.setObjectName(_fromUtf8("pick_send_btn"))
        self.pick_clear_btn = QtGui.QPushButton(PickPoint)
        self.pick_clear_btn.setGeometry(QtCore.QRect(390, 540, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_clear_btn.setFont(font)
        self.pick_clear_btn.setObjectName(_fromUtf8("pick_clear_btn"))
        self.pick_refresh_btn = QtGui.QPushButton(PickPoint)
        self.pick_refresh_btn.setEnabled(False)
        self.pick_refresh_btn.setGeometry(QtCore.QRect(390, 570, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_refresh_btn.setFont(font)
        self.pick_refresh_btn.setObjectName(_fromUtf8("pick_refresh_btn"))
        self.pick_path_btn = QtGui.QPushButton(PickPoint)
        self.pick_path_btn.setGeometry(QtCore.QRect(300, 540, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_path_btn.setFont(font)
        self.pick_path_btn.setObjectName(_fromUtf8("pick_path_btn"))
        self.pick_obstacle_btn = QtGui.QPushButton(PickPoint)
        self.pick_obstacle_btn.setGeometry(QtCore.QRect(300, 570, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_obstacle_btn.setFont(font)
        self.pick_obstacle_btn.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.pick_obstacle_btn.setObjectName(_fromUtf8("pick_obstacle_btn"))
        self.pick_curLoc_btn = QtGui.QPushButton(PickPoint)
        self.pick_curLoc_btn.setGeometry(QtCore.QRect(300, 510, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_curLoc_btn.setFont(font)
        self.pick_curLoc_btn.setObjectName(_fromUtf8("pick_curLoc_btn"))
        self.pick_takeoff_btn = QtGui.QPushButton(PickPoint)
        self.pick_takeoff_btn.setGeometry(QtCore.QRect(210, 510, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_takeoff_btn.setFont(font)
        self.pick_takeoff_btn.setObjectName(_fromUtf8("pick_takeoff_btn"))
        self.pick_startMission_btn = QtGui.QPushButton(PickPoint)
        self.pick_startMission_btn.setGeometry(QtCore.QRect(210, 540, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_startMission_btn.setFont(font)
        self.pick_startMission_btn.setObjectName(_fromUtf8("pick_startMission_btn"))
        self.pick_abortMission_btn = QtGui.QPushButton(PickPoint)
        self.pick_abortMission_btn.setGeometry(QtCore.QRect(210, 570, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_abortMission_btn.setFont(font)
        self.pick_abortMission_btn.setObjectName(_fromUtf8("pick_abortMission_btn"))
        self.pick_land_btn = QtGui.QPushButton(PickPoint)
        self.pick_land_btn.setGeometry(QtCore.QRect(210, 600, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_land_btn.setFont(font)
        self.pick_land_btn.setObjectName(_fromUtf8("pick_land_btn"))
        self.pick_return_btn = QtGui.QPushButton(PickPoint)
        self.pick_return_btn.setGeometry(QtCore.QRect(210, 630, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_return_btn.setFont(font)
        self.pick_return_btn.setObjectName(_fromUtf8("pick_return_btn"))
        self.groupBox = QtGui.QGroupBox(PickPoint)
        self.groupBox.setGeometry(QtCore.QRect(200, 490, 271, 171))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.pp_webView.raise_()
        self.groupBox.raise_()
        self.pp_testbrowser.raise_()
        self.pick_send_btn.raise_()
        self.pick_clear_btn.raise_()
        self.pick_refresh_btn.raise_()
        self.pick_path_btn.raise_()
        self.pick_obstacle_btn.raise_()
        self.pick_curLoc_btn.raise_()
        self.pick_takeoff_btn.raise_()
        self.pick_startMission_btn.raise_()
        self.pick_abortMission_btn.raise_()
        self.pick_land_btn.raise_()
        self.pick_return_btn.raise_()

        self.retranslateUi(PickPoint)
        QtCore.QObject.connect(self.pick_refresh_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pp_webView.reload)
        QtCore.QMetaObject.connectSlotsByName(PickPoint)

    def retranslateUi(self, PickPoint):
        PickPoint.setWindowTitle(_translate("PickPoint", "地图选点", None))
        self.pick_send_btn.setText(_translate("PickPoint", "发送轨迹", None))
        self.pick_clear_btn.setText(_translate("PickPoint", "重置", None))
        self.pick_refresh_btn.setText(_translate("PickPoint", "刷新", None))
        self.pick_path_btn.setText(_translate("PickPoint", "轨迹模式", None))
        self.pick_obstacle_btn.setText(_translate("PickPoint", "障碍模式", None))
        self.pick_curLoc_btn.setText(_translate("PickPoint", "当前位置", None))
        self.pick_takeoff_btn.setText(_translate("PickPoint", "起飞", None))
        self.pick_startMission_btn.setText(_translate("PickPoint", "执行任务", None))
        self.pick_abortMission_btn.setText(_translate("PickPoint", "终止任务", None))
        self.pick_land_btn.setText(_translate("PickPoint", "降落", None))
        self.pick_return_btn.setText(_translate("PickPoint", "返航", None))
        self.groupBox.setTitle(_translate("PickPoint", "Control", None))

from PyQt4 import QtWebKit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    PickPoint = QtGui.QDialog()
    ui = Ui_PickPoint()
    ui.setupUi(PickPoint)
    PickPoint.show()
    sys.exit(app.exec_())

