# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Harry\Documents\PyQtProjects\socket_func_pyqt\ui\pick_point.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PickPoint(object):
    def setupUi(self, PickPoint):
        PickPoint.setObjectName(_fromUtf8("PickPoint"))
        PickPoint.resize(944, 720)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PickPoint.sizePolicy().hasHeightForWidth())
        PickPoint.setSizePolicy(sizePolicy)
        PickPoint.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        PickPoint.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        PickPoint.setSizeGripEnabled(True)
        self.pp_webView = QtWebKit.QWebView(PickPoint)
        self.pp_webView.setGeometry(QtCore.QRect(0, 0, 1031, 741))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pp_webView.sizePolicy().hasHeightForWidth())
        self.pp_webView.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pp_webView.setFont(font)
        self.pp_webView.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pp_webView.setMouseTracking(True)
        self.pp_webView.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        #self.pp_webView.setUrl(QtCore.QUrl(_fromUtf8("file:///C:/Users/Harry/Documents/PyQtProjects/socket_func_pyqt/websrc/pick_point_2.html")))
        import os
        self.pp_webView.setUrl(
            QtCore.QUrl(_fromUtf8("file:///" + '/'.join(os.getcwd().split('\\')) + "/websrc/pick_point_2.html")))
        self.pp_webView.setObjectName(_fromUtf8("pp_webView"))
        self.groupBox = QtGui.QGroupBox(PickPoint)
        self.groupBox.setGeometry(QtCore.QRect(0, 490, 951, 231))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.pick_status_label = QtGui.QLabel(self.groupBox)
        self.pick_status_label.setGeometry(QtCore.QRect(620, 25, 100, 16))
        self.pick_status_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pick_status_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pick_status_label.setObjectName(_fromUtf8("pick_status_label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(530, 25, 90, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pick_show_curPath_btn = QtGui.QPushButton(self.groupBox)
        self.pick_show_curPath_btn.setGeometry(QtCore.QRect(20, 20, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_show_curPath_btn.setFont(font)
        self.pick_show_curPath_btn.setObjectName(_fromUtf8("pick_show_curPath_btn"))
        self.pick_param_check_btn = QtGui.QPushButton(self.groupBox)
        self.pick_param_check_btn.setGeometry(QtCore.QRect(120, 20, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_param_check_btn.setFont(font)
        self.pick_param_check_btn.setObjectName(_fromUtf8("pick_param_check_btn"))
        self.pp_param_speed = QtGui.QLineEdit(self.groupBox)
        self.pp_param_speed.setGeometry(QtCore.QRect(150, 80, 50, 23))
        self.pp_param_speed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pp_param_speed.setObjectName(_fromUtf8("pp_param_speed"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(110, 54, 41, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.pick_param_set_btn = QtGui.QPushButton(self.groupBox)
        self.pick_param_set_btn.setGeometry(QtCore.QRect(120, 200, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_param_set_btn.setFont(font)
        self.pick_param_set_btn.setObjectName(_fromUtf8("pick_param_set_btn"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(110, 83, 41, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.pp_param_height = QtGui.QLineEdit(self.groupBox)
        self.pp_param_height.setGeometry(QtCore.QRect(150, 50, 50, 23))
        self.pp_param_height.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pp_param_height.setObjectName(_fromUtf8("pp_param_height"))
        self.pick_curLoc_btn = QtGui.QPushButton(self.groupBox)
        self.pick_curLoc_btn.setGeometry(QtCore.QRect(20, 50, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_curLoc_btn.setFont(font)
        self.pick_curLoc_btn.setObjectName(_fromUtf8("pick_curLoc_btn"))
        self.pick_path_btn = QtGui.QPushButton(self.groupBox)
        self.pick_path_btn.setGeometry(QtCore.QRect(220, 50, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_path_btn.setFont(font)
        self.pick_path_btn.setObjectName(_fromUtf8("pick_path_btn"))
        self.pick_obstacle_btn = QtGui.QPushButton(self.groupBox)
        self.pick_obstacle_btn.setGeometry(QtCore.QRect(220, 80, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_obstacle_btn.setFont(font)
        self.pick_obstacle_btn.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.pick_obstacle_btn.setObjectName(_fromUtf8("pick_obstacle_btn"))
        self.pick_refresh_btn = QtGui.QPushButton(self.groupBox)
        self.pick_refresh_btn.setEnabled(False)
        self.pick_refresh_btn.setGeometry(QtCore.QRect(220, 200, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_refresh_btn.setFont(font)
        self.pick_refresh_btn.setObjectName(_fromUtf8("pick_refresh_btn"))
        self.pick_clear_btn = QtGui.QPushButton(self.groupBox)
        self.pick_clear_btn.setGeometry(QtCore.QRect(320, 110, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_clear_btn.setFont(font)
        self.pick_clear_btn.setObjectName(_fromUtf8("pick_clear_btn"))
        self.pick_send_btn = QtGui.QPushButton(self.groupBox)
        self.pick_send_btn.setGeometry(QtCore.QRect(320, 20, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_send_btn.setFont(font)
        self.pick_send_btn.setObjectName(_fromUtf8("pick_send_btn"))
        self.pick_reset_order_btn = QtGui.QPushButton(self.groupBox)
        self.pick_reset_order_btn.setGeometry(QtCore.QRect(320, 80, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_reset_order_btn.setFont(font)
        self.pick_reset_order_btn.setObjectName(_fromUtf8("pick_reset_order_btn"))
        self.pick_resend_btn = QtGui.QPushButton(self.groupBox)
        self.pick_resend_btn.setGeometry(QtCore.QRect(320, 50, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_resend_btn.setFont(font)
        self.pick_resend_btn.setObjectName(_fromUtf8("pick_resend_btn"))
        self.pick_return_btn = QtGui.QPushButton(self.groupBox)
        self.pick_return_btn.setGeometry(QtCore.QRect(420, 140, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_return_btn.setFont(font)
        self.pick_return_btn.setObjectName(_fromUtf8("pick_return_btn"))
        self.pick_abortMission_btn = QtGui.QPushButton(self.groupBox)
        self.pick_abortMission_btn.setGeometry(QtCore.QRect(420, 80, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_abortMission_btn.setFont(font)
        self.pick_abortMission_btn.setObjectName(_fromUtf8("pick_abortMission_btn"))
        self.pick_land_btn = QtGui.QPushButton(self.groupBox)
        self.pick_land_btn.setGeometry(QtCore.QRect(420, 110, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_land_btn.setFont(font)
        self.pick_land_btn.setObjectName(_fromUtf8("pick_land_btn"))
        self.pick_takeoff_btn = QtGui.QPushButton(self.groupBox)
        self.pick_takeoff_btn.setGeometry(QtCore.QRect(420, 20, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_takeoff_btn.setFont(font)
        self.pick_takeoff_btn.setObjectName(_fromUtf8("pick_takeoff_btn"))
        self.pick_startMission_btn = QtGui.QPushButton(self.groupBox)
        self.pick_startMission_btn.setGeometry(QtCore.QRect(420, 50, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_startMission_btn.setFont(font)
        self.pick_startMission_btn.setObjectName(_fromUtf8("pick_startMission_btn"))
        self.pp_testbrowser = QtGui.QTextBrowser(self.groupBox)
        self.pp_testbrowser.setGeometry(QtCore.QRect(510, 110, 421, 101))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pp_testbrowser.setFont(font)
        self.pp_testbrowser.setObjectName(_fromUtf8("pp_testbrowser"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(530, 45, 90, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(730, 25, 91, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(730, 45, 91, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(530, 65, 91, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(730, 65, 91, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.pick_time_label = QtGui.QLabel(self.groupBox)
        self.pick_time_label.setGeometry(QtCore.QRect(620, 45, 100, 16))
        self.pick_time_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pick_time_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pick_time_label.setObjectName(_fromUtf8("pick_time_label"))
        self.pick_longitude_label = QtGui.QLabel(self.groupBox)
        self.pick_longitude_label.setGeometry(QtCore.QRect(800, 25, 120, 16))
        self.pick_longitude_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pick_longitude_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pick_longitude_label.setObjectName(_fromUtf8("pick_longitude_label"))
        self.pick_latitude_label = QtGui.QLabel(self.groupBox)
        self.pick_latitude_label.setGeometry(QtCore.QRect(800, 45, 120, 16))
        self.pick_latitude_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pick_latitude_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pick_latitude_label.setObjectName(_fromUtf8("pick_latitude_label"))
        self.pick_height_label = QtGui.QLabel(self.groupBox)
        self.pick_height_label.setGeometry(QtCore.QRect(620, 65, 100, 16))
        self.pick_height_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pick_height_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pick_height_label.setObjectName(_fromUtf8("pick_height_label"))
        self.pick_speed_label = QtGui.QLabel(self.groupBox)
        self.pick_speed_label.setGeometry(QtCore.QRect(820, 65, 100, 16))
        self.pick_speed_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pick_speed_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pick_speed_label.setObjectName(_fromUtf8("pick_speed_label"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(510, 0, 421, 91))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.pp_param_return_speed = QtGui.QLineEdit(self.groupBox)
        self.pp_param_return_speed.setGeometry(QtCore.QRect(150, 140, 50, 23))
        self.pp_param_return_speed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pp_param_return_speed.setObjectName(_fromUtf8("pp_param_return_speed"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(80, 143, 71, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.pp_param_return_height = QtGui.QLineEdit(self.groupBox)
        self.pp_param_return_height.setGeometry(QtCore.QRect(150, 110, 50, 23))
        self.pp_param_return_height.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pp_param_return_height.setObjectName(_fromUtf8("pp_param_return_height"))
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(80, 113, 71, 20))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.pick_homeLoc_btn = QtGui.QPushButton(self.groupBox)
        self.pick_homeLoc_btn.setGeometry(QtCore.QRect(20, 80, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_homeLoc_btn.setFont(font)
        self.pick_homeLoc_btn.setObjectName(_fromUtf8("pick_homeLoc_btn"))
        self.pp_param_obstacle_distance = QtGui.QLineEdit(self.groupBox)
        self.pp_param_obstacle_distance.setGeometry(QtCore.QRect(150, 170, 50, 23))
        self.pp_param_obstacle_distance.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pp_param_obstacle_distance.setObjectName(_fromUtf8("pp_param_obstacle_distance"))
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(80, 173, 71, 20))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.pick_loadPath_btn = QtGui.QPushButton(self.groupBox)
        self.pick_loadPath_btn.setGeometry(QtCore.QRect(220, 20, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_loadPath_btn.setFont(font)
        self.pick_loadPath_btn.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.pick_loadPath_btn.setObjectName(_fromUtf8("pick_loadPath_btn"))
        self.pick_recordPoint_btn = QtGui.QPushButton(self.groupBox)
        self.pick_recordPoint_btn.setGeometry(QtCore.QRect(220, 140, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_recordPoint_btn.setFont(font)
        self.pick_recordPoint_btn.setObjectName(_fromUtf8("pick_recordPoint_btn"))
        self.pick_deleteRecord_btn = QtGui.QPushButton(self.groupBox)
        self.pick_deleteRecord_btn.setGeometry(QtCore.QRect(220, 170, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.pick_deleteRecord_btn.setFont(font)
        self.pick_deleteRecord_btn.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.pick_deleteRecord_btn.setObjectName(_fromUtf8("pick_deleteRecord_btn"))
        self.groupBox_2.raise_()
        self.pick_status_label.raise_()
        self.label_2.raise_()
        self.pick_show_curPath_btn.raise_()
        self.pick_param_check_btn.raise_()
        self.pp_param_speed.raise_()
        self.label_3.raise_()
        self.pick_param_set_btn.raise_()
        self.label_4.raise_()
        self.pp_param_height.raise_()
        self.pick_curLoc_btn.raise_()
        self.pick_path_btn.raise_()
        self.pick_obstacle_btn.raise_()
        self.pick_refresh_btn.raise_()
        self.pick_clear_btn.raise_()
        self.pick_send_btn.raise_()
        self.pick_reset_order_btn.raise_()
        self.pick_resend_btn.raise_()
        self.pick_return_btn.raise_()
        self.pick_abortMission_btn.raise_()
        self.pick_land_btn.raise_()
        self.pick_takeoff_btn.raise_()
        self.pick_startMission_btn.raise_()
        self.pp_testbrowser.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.pick_time_label.raise_()
        self.pick_longitude_label.raise_()
        self.pick_latitude_label.raise_()
        self.pick_height_label.raise_()
        self.pick_speed_label.raise_()
        self.pp_param_return_speed.raise_()
        self.label_10.raise_()
        self.pp_param_return_height.raise_()
        self.label_11.raise_()
        self.pick_homeLoc_btn.raise_()
        self.pp_param_obstacle_distance.raise_()
        self.label_12.raise_()
        self.pick_loadPath_btn.raise_()
        self.pick_recordPoint_btn.raise_()
        self.pick_deleteRecord_btn.raise_()

        self.retranslateUi(PickPoint)
        QtCore.QObject.connect(self.pick_refresh_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pp_webView.reload)
        QtCore.QMetaObject.connectSlotsByName(PickPoint)

    def retranslateUi(self, PickPoint):
        PickPoint.setWindowTitle(_translate("PickPoint", "轨迹设置", None))
        self.groupBox.setTitle(_translate("PickPoint", "Control", None))
        self.pick_status_label.setText(_translate("PickPoint", "无", None))
        self.label_2.setText(_translate("PickPoint", "飞行器状态：", None))
        self.pick_show_curPath_btn.setText(_translate("PickPoint", "开启跟踪", None))
        self.pick_param_check_btn.setText(_translate("PickPoint", "参数查询", None))
        self.pp_param_speed.setText(_translate("PickPoint", "1.0", None))
        self.label_3.setText(_translate("PickPoint", "高度:", None))
        self.pick_param_set_btn.setText(_translate("PickPoint", "参数设置", None))
        self.label_4.setText(_translate("PickPoint", "速度:", None))
        self.pp_param_height.setText(_translate("PickPoint", "2.0", None))
        self.pick_curLoc_btn.setText(_translate("PickPoint", "当前位置", None))
        self.pick_path_btn.setText(_translate("PickPoint", "轨迹模式", None))
        self.pick_obstacle_btn.setText(_translate("PickPoint", "障碍模式", None))
        self.pick_refresh_btn.setText(_translate("PickPoint", "刷新", None))
        self.pick_clear_btn.setText(_translate("PickPoint", "清除设置", None))
        self.pick_send_btn.setText(_translate("PickPoint", "发送轨迹", None))
        self.pick_reset_order_btn.setText(_translate("PickPoint", "清除命令", None))
        self.pick_resend_btn.setText(_translate("PickPoint", "重新发送", None))
        self.pick_return_btn.setText(_translate("PickPoint", "返航", None))
        self.pick_abortMission_btn.setText(_translate("PickPoint", "终止任务", None))
        self.pick_land_btn.setText(_translate("PickPoint", "降落", None))
        self.pick_takeoff_btn.setText(_translate("PickPoint", "起飞", None))
        self.pick_startMission_btn.setText(_translate("PickPoint", "执行任务", None))
        self.label_5.setText(_translate("PickPoint", "更新时间：", None))
        self.label_6.setText(_translate("PickPoint", "经度：", None))
        self.label_7.setText(_translate("PickPoint", "纬度：", None))
        self.label_8.setText(_translate("PickPoint", "离地高度：", None))
        self.label_9.setText(_translate("PickPoint", "速度：", None))
        self.pick_time_label.setText(_translate("PickPoint", "无", None))
        self.pick_longitude_label.setText(_translate("PickPoint", "无", None))
        self.pick_latitude_label.setText(_translate("PickPoint", "无", None))
        self.pick_height_label.setText(_translate("PickPoint", "无", None))
        self.pick_speed_label.setText(_translate("PickPoint", "无", None))
        self.groupBox_2.setTitle(_translate("PickPoint", "Status", None))
        self.pp_param_return_speed.setText(_translate("PickPoint", "10.0", None))
        self.label_10.setText(_translate("PickPoint", "返航速度:", None))
        self.pp_param_return_height.setText(_translate("PickPoint", "100.0", None))
        self.label_11.setText(_translate("PickPoint", "返航高度:", None))
        self.pick_homeLoc_btn.setText(_translate("PickPoint", "返航点", None))
        self.pp_param_obstacle_distance.setText(_translate("PickPoint", "2.0", None))
        self.label_12.setText(_translate("PickPoint", "避障距离:", None))
        self.pick_loadPath_btn.setText(_translate("PickPoint", "载入轨迹", None))
        self.pick_recordPoint_btn.setText(_translate("PickPoint", "记录坐标", None))
        self.pick_deleteRecord_btn.setText(_translate("PickPoint", "删除记录", None))

from PyQt4 import QtWebKit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    PickPoint = QtGui.QDialog()
    ui = Ui_PickPoint()
    ui.setupUi(PickPoint)
    PickPoint.show()
    sys.exit(app.exec_())

