# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Harry\Documents\PyQtProjects\socket_func_pyqt\ui\yingyan_web.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_yingyan_web(object):
    def setupUi(self, yingyan_web):
        yingyan_web.setObjectName(_fromUtf8("yingyan_web"))
        yingyan_web.resize(1280, 720)
        yingyan_web.setMinimumSize(QtCore.QSize(1280, 720))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        yingyan_web.setFont(font)
        yingyan_web.setSizeGripEnabled(True)
        self.webView = QtWebKit.QWebView(yingyan_web)
        self.webView.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webView.sizePolicy().hasHeightForWidth())
        self.webView.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.webView.setFont(font)
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("file:///C:/Users/Harry/Documents/PyQtProjects/socket_func_pyqt/websrc/yinyandemo/index.html")))
        import os
        self.webView.setUrl(
            QtCore.QUrl(_fromUtf8("file:///" + '/'.join(os.getcwd().split('\\')) + "/websrc/yinyandemo/index.html")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.web_fresh_btn = QtGui.QPushButton(yingyan_web)
        self.web_fresh_btn.setEnabled(True)
        self.web_fresh_btn.setGeometry(QtCore.QRect(50, 695, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.web_fresh_btn.setFont(font)
        self.web_fresh_btn.setCheckable(False)
        self.web_fresh_btn.setObjectName(_fromUtf8("web_fresh_btn"))
        self.web_emit_btn = QtGui.QPushButton(yingyan_web)
        self.web_emit_btn.setEnabled(False)
        self.web_emit_btn.setGeometry(QtCore.QRect(170, 695, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.web_emit_btn.setFont(font)
        self.web_emit_btn.setCheckable(False)
        self.web_emit_btn.setObjectName(_fromUtf8("web_emit_btn"))
        self.web_group_box = QtGui.QGroupBox(yingyan_web)
        self.web_group_box.setGeometry(QtCore.QRect(20, 550, 291, 141))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.web_group_box.setFont(font)
        self.web_group_box.setAutoFillBackground(True)
        self.web_group_box.setObjectName(_fromUtf8("web_group_box"))
        self.web_time_label = QtGui.QLabel(self.web_group_box)
        self.web_time_label.setGeometry(QtCore.QRect(100, 20, 150, 12))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.web_time_label.setFont(font)
        self.web_time_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.web_time_label.setObjectName(_fromUtf8("web_time_label"))
        self.web_const_time_label = QtGui.QLabel(self.web_group_box)
        self.web_const_time_label.setGeometry(QtCore.QRect(30, 20, 54, 12))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.web_const_time_label.setFont(font)
        self.web_const_time_label.setObjectName(_fromUtf8("web_const_time_label"))
        self.web_recdata_label = QtGui.QLabel(self.web_group_box)
        self.web_recdata_label.setGeometry(QtCore.QRect(100, 110, 150, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.web_recdata_label.setFont(font)
        self.web_recdata_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.web_recdata_label.setObjectName(_fromUtf8("web_recdata_label"))
        self.label = QtGui.QLabel(self.web_group_box)
        self.label.setGeometry(QtCore.QRect(30, 40, 54, 12))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.web_group_box)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 54, 12))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.web_group_box)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 54, 12))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.web_longi_label = QtGui.QLabel(self.web_group_box)
        self.web_longi_label.setGeometry(QtCore.QRect(100, 40, 150, 12))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.web_longi_label.setFont(font)
        self.web_longi_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.web_longi_label.setObjectName(_fromUtf8("web_longi_label"))
        self.web_lati_label = QtGui.QLabel(self.web_group_box)
        self.web_lati_label.setGeometry(QtCore.QRect(100, 60, 150, 12))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.web_lati_label.setFont(font)
        self.web_lati_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.web_lati_label.setObjectName(_fromUtf8("web_lati_label"))
        self.web_altitu_label = QtGui.QLabel(self.web_group_box)
        self.web_altitu_label.setGeometry(QtCore.QRect(100, 80, 150, 12))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.web_altitu_label.setFont(font)
        self.web_altitu_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.web_altitu_label.setObjectName(_fromUtf8("web_altitu_label"))
        self.label_4 = QtGui.QLabel(self.web_group_box)
        self.label_4.setGeometry(QtCore.QRect(30, 100, 54, 12))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.web_speed_label = QtGui.QLabel(self.web_group_box)
        self.web_speed_label.setGeometry(QtCore.QRect(100, 100, 150, 12))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.web_speed_label.setFont(font)
        self.web_speed_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.web_speed_label.setObjectName(_fromUtf8("web_speed_label"))
        self.web_const_time_label_2 = QtGui.QLabel(self.web_group_box)
        self.web_const_time_label_2.setGeometry(QtCore.QRect(255, 80, 54, 12))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.web_const_time_label_2.setFont(font)
        self.web_const_time_label_2.setObjectName(_fromUtf8("web_const_time_label_2"))
        self.web_const_time_label_3 = QtGui.QLabel(self.web_group_box)
        self.web_const_time_label_3.setGeometry(QtCore.QRect(255, 100, 54, 12))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.web_const_time_label_3.setFont(font)
        self.web_const_time_label_3.setObjectName(_fromUtf8("web_const_time_label_3"))
        self.label_5 = QtGui.QLabel(self.web_group_box)
        self.label_5.setGeometry(QtCore.QRect(30, 120, 61, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.webView.raise_()
        self.web_group_box.raise_()
        self.web_fresh_btn.raise_()
        self.web_emit_btn.raise_()

        self.retranslateUi(yingyan_web)
        QtCore.QObject.connect(self.web_fresh_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.webView.reload)
        QtCore.QMetaObject.connectSlotsByName(yingyan_web)

    def retranslateUi(self, yingyan_web):
        yingyan_web.setWindowTitle(_translate("yingyan_web", "历史轨迹", None))
        self.web_fresh_btn.setText(_translate("yingyan_web", "刷新", None))
        self.web_emit_btn.setText(_translate("yingyan_web", "退出", None))
        self.web_group_box.setTitle(_translate("yingyan_web", "DATA", None))
        self.web_time_label.setText(_translate("yingyan_web", "None", None))
        self.web_const_time_label.setText(_translate("yingyan_web", "TIME:", None))
        self.web_recdata_label.setText(_translate("yingyan_web", "None", None))
        self.label.setText(_translate("yingyan_web", "LONGI:", None))
        self.label_2.setText(_translate("yingyan_web", "LATI:", None))
        self.label_3.setText(_translate("yingyan_web", "ALTIT:", None))
        self.web_longi_label.setText(_translate("yingyan_web", "None", None))
        self.web_lati_label.setText(_translate("yingyan_web", "None", None))
        self.web_altitu_label.setText(_translate("yingyan_web", "None", None))
        self.label_4.setText(_translate("yingyan_web", "SPEED:", None))
        self.web_speed_label.setText(_translate("yingyan_web", "None", None))
        self.web_const_time_label_2.setText(_translate("yingyan_web", "m", None))
        self.web_const_time_label_3.setText(_translate("yingyan_web", "m/s", None))
        self.label_5.setText(_translate("yingyan_web", "STATUS:", None))

from PyQt4 import QtWebKit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    yingyan_web = QtGui.QDialog()
    ui = Ui_yingyan_web()
    ui.setupUi(yingyan_web)
    yingyan_web.show()
    sys.exit(app.exec_())

